// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlCS3PEJHLKLQ_9U2nqtoJ8zSmBisgaCY',
    appId: '1:853112760627:web:f313f6f6b5532da0627646',
    messagingSenderId: '853112760627',
    projectId: 'todo-app-c2',
    authDomain: 'todo-app-c2.firebaseapp.com',
    storageBucket: 'todo-app-c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMC6HhKegs20TtFjsDAstREvLxNwgg1Bc',
    appId: '1:853112760627:android:7546bc876ce66ca7627646',
    messagingSenderId: '853112760627',
    projectId: 'todo-app-c2',
    storageBucket: 'todo-app-c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOUs41hS3psZVaTGrmn5wdFmRg7vqVgSs',
    appId: '1:853112760627:ios:385ef8833161667a627646',
    messagingSenderId: '853112760627',
    projectId: 'todo-app-c2',
    storageBucket: 'todo-app-c2.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOUs41hS3psZVaTGrmn5wdFmRg7vqVgSs',
    appId: '1:853112760627:ios:385ef8833161667a627646',
    messagingSenderId: '853112760627',
    projectId: 'todo-app-c2',
    storageBucket: 'todo-app-c2.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlCS3PEJHLKLQ_9U2nqtoJ8zSmBisgaCY',
    appId: '1:853112760627:web:4a64525ce5512d6e627646',
    messagingSenderId: '853112760627',
    projectId: 'todo-app-c2',
    authDomain: 'todo-app-c2.firebaseapp.com',
    storageBucket: 'todo-app-c2.appspot.com',
  );
}
